### ISSUE TITLE
mt_irc doesn't show timed-out messages

### ISSUE THREAD

**Issue by VanessaE** [kaeza/minetest-tools#1]
Minetest server and IRC mod now indicate whether the user timed-out from the game, versus simply leaving.  I think other quit reasons like being kicked are present also, not sure.

The mt_irc.py script doesn't echo these messages through.

**Comment by kaeza** [comment]
Didn't notice this issue was opened.

Fixed by https://github.com/kaeza/minetest-tools/commit/444867feee6bb326a21bdace44a4a37545a6fc8c (and https://github.com/kaeza/minetest-tools/commit/0944fdc25a12c562bb55e97cb600203358a464c1).
